Convert from the `chrono` crate to the `time` crate
brittlq/brittlq pull request #30
Opened 2021-12-20 04:01 UTC by pxslip

A few places here where I'm not sure about rust best practices/semantics. I'll add comments in the appropriate places.

2021-12-20 04:03 UTC, pxslip commented on src/chatbot/commands.rs
> +                    .await;
Supposedly `time::Duration` has a function `abs_std` that converts a, potentially negative, Duration to `std::time::Duration`. Attempting to use it introduced a compiler error indicating the method was private. The alternative is just to build a new `std::time::Duration` as here.

2021-12-20 04:04 UTC, pxslip commented on src/lib.rs
> +    s.serialize_str(&formatted.unwrap()) //unwrapping here, good practice or bad?
I'm not sure semantically/best practice for `let` vs `const` here. An alternative implementation could look like:

```rust
    let format = format_description!("[hour]:[minute]:[second]");
    let formatted = date_time.format(&format);
```

Not sure if there is a preference, and if so why.

2021-12-20 04:06 UTC, pxslip commented
Should also note that I used `unwrap` a few times. If my brain is following the logic properly I've used them safely. If that is not the case let me know.

2021-12-20 16:46 UTC, trollham requested changes

2021-12-20 16:46 UTC, trollham commented on src/chatbot/commands.rs
> +                    .await;
We don't allow for the creation of commands with a negative duration for the Wait action, see the implementation of the action_parser (if you can stomach it; that code is a mess). That makes it safe to unwrap here.

There's a conversion function provided as part of the `core::convert::TryFrom` trait, and `time::Duration` specializes an implementation for `std::time::Duration`. See the examples provided [here](https://github.com/time-rs/time/blob/8b78d3f0ee12e8466cacc035c1d3bd953484c84f/tests/integration/duration.rs#L381).

2021-12-20 16:46 UTC, trollham commented on src/lib.rs
> +    s.serialize_str(&formatted.unwrap()) //unwrapping here, good practice or bad?
`const` is a compile-time constant. Similar to `static`, except rather than refer to a place in memory, it substitutes the value in for the name directly. Think of it as similar to C's preprocessor macros, but constrained to values, not expressions (besides `const fn` expressions IIRC, but that's another can of worms). 

Can we switch this to use RFC 339 instead of the hacked H:M:S I put here originally? `time` provides a formatter for it, and it'd be better to use something standardized. If the front-end needs less info in that column we can handle it there, but for now I think it's fine to just send the entire RFC 339-formatted string.

2021-12-20 16:46 UTC, trollham commented on Cargo.toml
> +time = { version = "0.3.5", features = ["serde", "formatting", "macros", "local-offset"] }
I think we can leave off `macros` as a dependency, since we don't need to perform compile-time timestamp validation

2021-12-20 16:46 UTC, trollham commented on Cargo.toml
> +time = { version = "0.3.5", features = ["serde", "formatting", "macros", "local-offset"] }
Please remove `chrono` as a dependency.

2021-12-20 18:26 UTC, pxslip commented on Cargo.toml
> +time = { version = "0.3.5", features = ["serde", "formatting", "macros", "local-offset"] }
Done and done.

2021-12-20 18:31 UTC, pxslip commented
Rust type conversions are odd beasts. Though the explicit error handling is impressive.

These commits implement RFC3339 for serialization, improves the `time::Duration` -> `std::time::Duration` type conversion, and removes `chrono` and the `macro` feature.

2022-01-05 19:37 UTC, trollham approved these changes

2022-01-05 19:37 UTC, merged